### ISSUE TITLE
Зачем реализовывать Comparable если возвращаете 0?

### ISSUE THREAD

**Issue by coursar** [idris-musin/CarCatalog#3]
https://github.com/idris-musin/CarCatalog/blob/f1a16fcff69a0716f6ac5cd8de58420038389e8a/src/main/java/ru/itpark/Catalog.java#L70-L73

**Comment by idris-musin** [comment]
Исправил на сортировку по алфавиту:

https://github.com/idris-musin/CarCatalog/blob/42fcca86aba33f7726ba0749be37f89c20439084/src/main/java/ru/itpark/Catalog.java#L73-L76
